### ISSUE TITLE
Cambios en Wallet BTC

### ISSUE THREAD

**Issue by hvts83** [hvts83/retireyoung#33]
Eliminar campo de Wallet BTC para realizar los retiros
Añadir campo de Wallet BTC en perfil de usuario

**Comment by alukra** [comment]
ALTER TABLE `users`
ADD `btc` varchar(255) COLLATE 'utf8_unicode_ci' NULL AFTER `name`;

ALTER TABLE `retire`
DROP `btc`;

cambios en base de datos
