### ISSUE TITLE
Cambios de Solicitudes de Retiro

### ISSUE THREAD

**Issue by hvts83** [hvts83/retireyoung#34]
Usuario

- Mostrar estado de la solicitud
- Cuando solicite el retiro que muestre la cantidad máxima a retirar según el plan adquirido 

- Para planes de fondo de inversión no mostrar cantidad, solo mostrar el plan adquirido
- Remover cantidad a retirar
- Remover campo de wallet btc en formulario

Admin

- Cuando se envíe la solicitud debe enviar el dato de la wallet btc que el usuario añadió en su perfil

**Comment by alukra** [comment]
SELECT user_plans.id, transaction_id, plans.name AS 'plan', transaction.name AS 'transaccion', SUM(amount)  FROM user_plans
INNER JOIN plans ON user_plans.plan_id = plans.id 
INNER JOIN user_transaction ON  user_transaction.user_plan_id = user_plans.id
INNER JOIN transaction ON transaction_id = transaction.id
WHERE user_id = 39 AND user_plans.status = 1
GROUP BY user_plans.id, transaction_id

Consulta momentanea para adquirir los datos a mostrar para los planes
